# The destructive migration cop is disabled for now, but we want to keep it in the config
# so that we can enable it in the future when we are ready to enforce it.

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-graphql
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails
  # - ./rubocop/no_destructive_migration.rb

AllCops:
  Exclude:
    - '**/*.axlsx'
    - '.git/**/*'
    - 'bin/**/*'
    - 'circle.yml'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/structure.sql'
    - 'Guardfile'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'node_modules/**/*'
    - 'Rakefile'
    - 'README.md'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'
  NewCops: enable

# If the cop is not mentioned here, then we are using the defualts cops
# The default config can be found at https://github.com/rubocop/rubocop/blob/v1.60.2/config/default.yml
# Documentation can be found at https://docs.rubocop.org/rubocop/1.60/cops.html

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle:
  - key
  - table
  EnforcedColonStyle:
  - key
  - table
Layout/LineContinuationSpacing:
  EnforcedStyle: no_space
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Lint/AmbiguousOperator:
  Enabled: false
Lint/FlipFlop:
  Enabled: false
Lint/Loop:
  Enabled: false
Lint/SymbolConversion:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Exclude:
  - spec/**/*
Metrics/BlockLength:
  Exclude:
  - lib/tasks/**/*
  - spec/**/*
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 15
  Exclude:
  - spec/**/*
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
Metrics/ModuleLength:
  Max: 100
  Exclude:
  - spec/**/*
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Naming/PredicateName:
  ForbiddenPrefixes:
  - is_

Style/CollectionMethods:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/HashLikeCase:
  MinBranchesCount: 4
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/MethodCalledOnDoEndBlock:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'
    '%W': '()'
Style/RaiseArgs:
  Enabled: false
Style/SignalException:
  EnforcedStyle: semantic
Style/SingleArgumentDig:
  Enabled: false
Style/StringConcatenation:
  Mode: conservative
Style/WordArray:
  WordRegex: !ruby/regexp /\A[\p{Word}]+\z/

# for rubocop-rails
# Documentation can be found at https://docs.rubocop.org/rubocop-rails/2.25/cops_rails.html

Rails/FilePath:
  Enabled: false
Rails/FindBy:
  IgnoreWhereFirst: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/ToFormattedS:
  EnforcedStyle: to_formatted_s
Rails/WhereExists:
  EnforcedStyle: where

# for rubocop-rspec
# Documentation can be found at https://docs.rubocop.org/rubocop-rspec/3.0/cops_rspec.html

RSpec/AlignLeftLetBrace:
  Enabled: true
RSpec/AnyInstance:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/ExpectInHook:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/InstanceVariable:
  AssignmentOnly: true
RSpec/LetSetup:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false

# for rubocop-capybara
# Documentation can be found at https://docs.rubocop.org/rubocop-capybara/2.21/cops_capybara.html

Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: link_or_button
Capybara/NegationMatcher:
  EnforcedStyle: not_to

# for rubocop-performance
# Documentation can be found at https://docs.rubocop.org/rubocop-performance/1.21/cops_performance.html

Performance/CaseWhenSplat:
  Enabled: true
Performance/ChainArrayAllocation:
  Enabled: true
Performance/IoReadlines:
  Enabled: true
Performance/SelectMap:
  Enabled: true

# for rubocop-graphql
# Documentation can be found at https://www.rubydoc.info/gems/rubocop-graphql/1.5.3/RuboCop/Cop/GraphQL

GraphQL/GraphqlName:
  Enabled: false
GraphQL/MaxComplexitySchema:
  Enabled: false
GraphQL/MaxDepthSchema:
  Enabled: false

# Local overrides for this repo

Style/ClassAndModuleChildren:
  Enabled: false

# Custom cop to enforce Expand/Contract on migrations
# Registries/NoDestructiveMigration:
#   Enabled: true
#   Include:
#     - "db/migrate/**/*.rb"
#   Exclude:
#     - "db/schema.rb"
#     - "db/structure.sql"
