plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails
  - rubocop-qcustom

AllCops:
  Exclude:
    - '**/*.axlsx'
    - '.git/**/*'
    - 'bin/**/*'
    - 'circle.yml'
    - 'config/**/*'
    - 'db/**/*'
    - 'Guardfile'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'node_modules/**/*'
    - 'Rakefile'
    - 'README.md'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'
  NewCops: enable

# If the cop is not mentioned here, then we are using the defualts cops
# The default config can be found at https://github.com/rubocop/rubocop/blob/v1.77.0/config/default.yml
# Documentation can be found at https://docs.rubocop.org/rubocop/1.77/cops.html

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle:
  - key
  - table
  EnforcedColonStyle:
  - key
  - table
Layout/LineContinuationSpacing:
  EnforcedStyle: no_space
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Lint/AmbiguousOperator:
  Enabled: false
Lint/FlipFlop:
  Enabled: false
Lint/Loop:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: true
Lint/SymbolConversion:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Exclude:
  - spec/**/*
Metrics/BlockLength:
  Exclude:
  - lib/tasks/**/*
  - spec/**/*
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 15
  Exclude:
  - spec/**/*
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
Metrics/ModuleLength:
  Max: 100
  Exclude:
  - spec/**/*
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Naming/PredicatePrefix:
  ForbiddenPrefixes:
  - is_

Style/CollectionMethods:
  Enabled: true
Style/CollectionQuerying:
  Enabled: false
Style/ComparableBetween:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/HashLikeCase:
  MinBranchesCount: 4
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/MethodCalledOnDoEndBlock:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/SafeNavigationChainLength:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'
    '%W': '()'
Style/RaiseArgs:
  Enabled: false
Style/SignalException:
  EnforcedStyle: semantic
Style/SingleArgumentDig:
  Enabled: false
Style/StringConcatenation:
  Mode: conservative
Style/WordArray:
  WordRegex: !ruby/regexp /\A[\p{Word}]+\z/

# for rubocop-rails
# Documentation can be found at https://docs.rubocop.org/rubocop-rails/2.33/cops_rails.html

Rails/CompactBlank:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/FindBy:
  IgnoreWhereFirst: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/ToFormattedS:
  EnforcedStyle: to_formatted_s
Rails/WhereExists:
  EnforcedStyle: where

# for rubocop-rspec
# Documentation can be found at https://docs.rubocop.org/rubocop-rspec/3.7/cops_rspec.html

RSpec/AlignLeftLetBrace:
  Enabled: true
RSpec/AnyInstance:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/ExpectInHook:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/InstanceVariable:
  AssignmentOnly: true
RSpec/LetSetup:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false

# for rubocop-capybara
# Documentation can be found at https://docs.rubocop.org/rubocop-capybara/cops_capybara.html


Capybara/AmbiguousClick:
  Enabled: false
Capybara/ClickLinkOrButtonStyle:
  Enabled: false
Capybara/NegationMatcherAfterVisit:
  Enabled: false
Capybara/NegationMatcher:
  EnforcedStyle: not_to

# for rubocop-performance
# Documentation can be found at https://docs.rubocop.org/rubocop-performance/1.26/cops_performance.html

Performance/CaseWhenSplat:
  Enabled: true
Performance/ChainArrayAllocation:
  Enabled: true
Performance/IoReadlines:
  Enabled: true
Performance/SelectMap:
  Enabled: true

# for Factory_bot
# Documentation can be found at https://docs.rubocop.org/rubocop-factory_bot/cops_factorybot.html

FactoryBot/AssociationStyle:
  Enabled: false

# Repos that do not have `config.infer_spec_type_from_file_location!` will want to disable `RSpec/Rails/InferredSpecType` in their local rubocop.yml
# This affects the following repos
  # q-apps-models
  # q-apps-support
  # json_api_helpers
  # reporting-data-mart

# For this file, you will need the following gems:
  # gem 'rubocop', '~> 1.77.0'
  # gem 'rubocop-capybara', '~> 2.22.0'
  # gem 'rubocop-performance', '~> 1.26.0'
  # gem 'rubocop-rails', '~> 2.33.3'
  # gem 'rubocop-rspec', '>= 3.7.0'
  # gem 'rubocop-rspec_rails', '~> 2.31.0'
  # gem(
  #   'rubocop-qcustom',
  #   tag: 'v0.0.1'
  #   git: 'git@github.com:q-centrix/rubocop-qcustom'
  # )
